### ISSUE TITLE
Add ability to create sub-folders

### ISSUE THREAD

**Issue by langdonx** [reesemclean/blueprint#34]
This is already saving me a ton of time, but it's still a 2-step process:

1. Right click, New Folder, enter name
2. Right click, New File from Template, enter name

I thought MAYBE I could get away with the setup below, but when I use `New File from Template`, nothing happens now, so I assume it's not supported:

![image](https://cloud.githubusercontent.com/assets/441982/26682943/2db4d162-46b0-11e7-967d-ae36d4991f6c.png)

If that worked, I could just do step #2 above and it'd create the sub-folder for me.

PS: This thing is amazing, thanks to everyone involved.

**Comment by reesemclean** [comment]
This is a good idea - recursively create all the folders!. It should be possible.

Just to double check something - in the folder example you gave. Would we need to check if that 'component' folder is already created - and if it is just skip creating it and put the subfolder in the existing 'component' folder? Or would you expect it to be recreated every time?

**Comment by langdonx** [comment]
Good question...

Personally, for this 1 scenario, if the folder already exists and has files/folders in it, I'd prefer it to just error out, letting me know it can't be created because it exists and isn't empty.  If it exists but is empty, then I don't see a problem just proceeding.

Although I imagine someone might have a scenario where they don't care about existing files/folders and just want to merge the new stuff in (maybe even overwriting any existing files).

How hard is it to prompt when files exist?

```
File "xxx.html" exists.  Overwrite?

[Overwrite] [Overwrite All] [Cancel]
```

**Comment by reesemclean** [comment]
Actually... I think we already have your case covered with the `createFilesInFolderWithPattern` option of the manifest.json file (Originally I was thinking you wanted to create the "Component" folder and the __kebabCase_name__ folder).

Create a manifest.json file in your template folder with something like:

{
    "createFilesInFolderWithPattern": "__kebabCase_name__"
}

This option is a bit hidden away though.

But... I just checked in something that will make it so what you have also works. It should also allow for nested folders of any depth.

Should be able to release it soon. Thanks!

P.S. I'd love for you to submit a pull request at https://github.com/reesemclean/blueprint-examples with you template(s). It would be great to expand that so that everyone could see how to do different things with it.

**Comment by reesemclean** [comment]
Version 1.3.0 with the ability to template folder names is now available! Thanks for the request!

**Comment by langdonx** [comment]
Works like a charm without the manifest.json settings.  Thank you!
